title: Use Podman on Windows 
remote_theme: just-the-docs/just-the-docs
heading_anchors: true
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

theme: jekyll-theme-slate